FROM node:18-alpine

LABEL maintainer="xkloveme <xkloveme@gmail.com>"

# 设置时区
ENV TZ=Asia/Shanghai

# 设置 npm 和 pnpm 配置
RUN npm config set registry https://registry.npmmirror.com && \
    npm install -g pnpm@9.11.0 && \
    pnpm config set registry https://registry.npmmirror.com && \
    # 设置时区
    apk add --no-cache tzdata && \
    ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && \
    echo $TZ > /etc/timezone

# 工作目录
WORKDIR /app

CMD ["node"]
